# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e667bd8c583481348a6dcb791a22eceee886df278e660d2edf78429271e3cd8c2caae49a90d87482e51dd37e56729f9fe0e73a57cd3d5fdcb1ea98c33f62b2da

test:
  secret_key_base: cf652179b3b5d7ab4d3d0d45d375e904288b121c27728bfbd59b4406f08c14e304d1c319be56e739011951d90e7207989d2f2cea259bbe3efed30ae30d6af816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
